repos:
  - repo: local
    hooks:
      - id: dart-format
        name: dart format
        entry: dart format .
        language: system
        pass_filenames: false
      - id: flutter-analyze
        name: flutter analyze
        entry: flutter analyze
        language: system
        pass_filenames: false
      - id: flutter-test
        name: flutter test
        entry: flutter test
        language: system
        pass_filenames: false
